# For local development, only database is running
#
# docker compose up -d
# uvicorn app.main:app --reload
#

services:
  default_database:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - default_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATABASE__DB}
      - POSTGRES_USER=${DATABASE__USERNAME}
      - POSTGRES_PASSWORD=${DATABASE__PASSWORD}
    env_file:
      - .env
    ports:
      - "${DATABASE__PORT}:5432"

  test_database:
    restart: unless-stopped
    image: postgres:latest
    volumes:
      - test_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "31234:5432"

volumes:
  test_database_data:
  default_database_data:
